# Generated by Django 5.1.7 on 2026-01-29 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastname', models.CharField(max_length=100)),
                ('firstname', models.CharField(max_length=100)),
                ('height', models.PositiveSmallIntegerField(help_text='Height in cm')),
                ('weight', models.FloatField(help_text='Weight in kg')),
            ],
        ),
    ]
